package tx

import (
	"github.com/cosmos/cosmos-sdk/client"
	"github.com/gorilla/mux"
)

// RegisterTxRoutes registers all transaction routes on the provided router.
func RegisterTxRoutes(clientCtx client.Context, r *mux.Router) {
	r.HandleFunc(
		"/issue/issue",
		issueCreateHandlerFn(clientCtx),
	).Methods("POST")
	r.HandleFunc(
		"/issue/transfer",
		transferHandlerFn(clientCtx),
	).Methods("POST")
	r.HandleFunc(
		"/issue/transfer_from",
		transferFromHandlerFn(clientCtx),
	).Methods("POST")
	r.HandleFunc(
		"/issue/approve",
		approveHandlerFn(clientCtx),
	).Methods("POST")
	r.HandleFunc(
		"/issue/increase_allowance",
		increaseAllowanceHandlerFn(clientCtx),
	).Methods("POST")
	r.HandleFunc(
		"/issue/decrease_allowance",
		decreaseAllowanceHandlerFn(clientCtx),
	).Methods("POST")
	r.HandleFunc(
		"/issue/mint",
		mintHandlerFn(clientCtx),
	).Methods("POST")
	r.HandleFunc(
		"/issue/burn",
		burnHandlerFn(clientCtx),
	).Methods("POST")
	r.HandleFunc(
		"/issue/burn_from",
		burnFromHandlerFn(clientCtx),
	).Methods("POST")
	r.HandleFunc(
		"/issue/transfer_ownership",
		transferOwnershipHandlerFn(clientCtx),
	).Methods("POST")
	r.HandleFunc(
		"/issue/disable_feature",
		disableFeatureHandlerFn(clientCtx),
	).Methods("POST")
	r.HandleFunc(
		"/issue/enable_feature",
		enableFeatureHandlerFn(clientCtx),
	).Methods("POST")
	r.HandleFunc(
		"/issue/features",
		featuresHandlerFn(clientCtx),
	).Methods("POST")
	r.HandleFunc(
		"/issue/description",
		descriptionHandlerFn(clientCtx),
	).Methods("POST")
	r.HandleFunc(
		"/issue/freeze",
		freezeHandlerFn(clientCtx),
	).Methods("POST")
	r.HandleFunc(
		"/issue/unfreeze",
		unfreezeHandlerFn(clientCtx),
	).Methods("POST")
}
