// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: issue/coin_issue.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CoinIssue struct {
	Id                 uint64                                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Issuer             string                                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty" yaml:"issuer"`
	Owner              string                                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty" yaml:"owner"`
	Denom              string                                 `protobuf:"bytes,4,opt,name=denom,proto3" json:"denom,omitempty"`
	Symbol             string                                 `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TotalSupply        github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,6,opt,name=total_supply,json=totalSupply,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"total_supply"`
	Decimals           int32                                  `protobuf:"varint,7,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Description        string                                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	IssueTime          int32                                  `protobuf:"varint,9,opt,name=issueTime,proto3" json:"issueTime,omitempty"`
	BurnOwnerDisabled  bool                                   `protobuf:"varint,10,opt,name=burn_owner_disabled,json=burnOwnerDisabled,proto3" json:"burn_owner_disabled,omitempty"`
	BurnHolderDisabled bool                                   `protobuf:"varint,11,opt,name=burn_holder_disabled,json=burnHolderDisabled,proto3" json:"burn_holder_disabled,omitempty"`
	BurnFromDisabled   bool                                   `protobuf:"varint,12,opt,name=burn_from_disabled,json=burnFromDisabled,proto3" json:"burn_from_disabled,omitempty"`
	FreezeDisabled     bool                                   `protobuf:"varint,13,opt,name=freeze_disabled,json=freezeDisabled,proto3" json:"freeze_disabled,omitempty"`
	MintDisabled       bool                                   `protobuf:"varint,14,opt,name=mint_disabled,json=mintDisabled,proto3" json:"mint_disabled,omitempty"`
}

func (m *CoinIssue) Reset()         { *m = CoinIssue{} }
func (m *CoinIssue) String() string { return proto.CompactTextString(m) }
func (*CoinIssue) ProtoMessage()    {}
func (*CoinIssue) Descriptor() ([]byte, []int) {
	return fileDescriptor_facae79e05f2b2dd, []int{0}
}
func (m *CoinIssue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CoinIssue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CoinIssue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CoinIssue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinIssue.Merge(m, src)
}
func (m *CoinIssue) XXX_Size() int {
	return m.Size()
}
func (m *CoinIssue) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinIssue.DiscardUnknown(m)
}

var xxx_messageInfo_CoinIssue proto.InternalMessageInfo

func (m *CoinIssue) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CoinIssue) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *CoinIssue) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *CoinIssue) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *CoinIssue) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *CoinIssue) GetDecimals() int32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *CoinIssue) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CoinIssue) GetIssueTime() int32 {
	if m != nil {
		return m.IssueTime
	}
	return 0
}

func (m *CoinIssue) GetBurnOwnerDisabled() bool {
	if m != nil {
		return m.BurnOwnerDisabled
	}
	return false
}

func (m *CoinIssue) GetBurnHolderDisabled() bool {
	if m != nil {
		return m.BurnHolderDisabled
	}
	return false
}

func (m *CoinIssue) GetBurnFromDisabled() bool {
	if m != nil {
		return m.BurnFromDisabled
	}
	return false
}

func (m *CoinIssue) GetFreezeDisabled() bool {
	if m != nil {
		return m.FreezeDisabled
	}
	return false
}

func (m *CoinIssue) GetMintDisabled() bool {
	if m != nil {
		return m.MintDisabled
	}
	return false
}

func init() {
	proto.RegisterType((*CoinIssue)(nil), "konstellation.issue.CoinIssue")
}

func init() { proto.RegisterFile("issue/coin_issue.proto", fileDescriptor_facae79e05f2b2dd) }

var fileDescriptor_facae79e05f2b2dd = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x92, 0x4d, 0x6e, 0x13, 0x31,
	0x18, 0x86, 0x33, 0x21, 0x09, 0x89, 0xf3, 0x43, 0xeb, 0x46, 0x95, 0x55, 0xa1, 0xc9, 0x28, 0x48,
	0x6d, 0x90, 0x60, 0x06, 0x89, 0x1d, 0xcb, 0x82, 0x10, 0x5d, 0x21, 0x06, 0x56, 0x6c, 0x46, 0xf3,
	0xe3, 0xa6, 0x56, 0x6d, 0x7f, 0xa3, 0xb1, 0x23, 0x08, 0xa7, 0xe0, 0x1a, 0xdc, 0xa4, 0xcb, 0x2e,
	0x11, 0x8b, 0x08, 0x25, 0x37, 0xe8, 0x09, 0x90, 0xbf, 0x09, 0x49, 0x56, 0x63, 0xbf, 0xcf, 0xf3,
	0x7e, 0x1a, 0x5b, 0x26, 0xa7, 0xc2, 0x98, 0x05, 0x8f, 0x72, 0x10, 0x3a, 0xc1, 0x65, 0x58, 0x56,
	0x60, 0x81, 0x9e, 0xdc, 0x82, 0x36, 0x96, 0x4b, 0x99, 0x5a, 0x01, 0x3a, 0x44, 0x74, 0x36, 0x9e,
	0xc3, 0x1c, 0x90, 0x47, 0x6e, 0x55, 0xab, 0xd3, 0x5f, 0x2d, 0xd2, 0x7b, 0x0b, 0x42, 0x5f, 0x39,
	0x87, 0x8e, 0x48, 0x53, 0x14, 0xcc, 0x0b, 0xbc, 0x59, 0x2b, 0x6e, 0x8a, 0x82, 0x3e, 0x27, 0x1d,
	0x2c, 0x57, 0xac, 0x19, 0x78, 0xb3, 0xde, 0xe5, 0xf1, 0xc3, 0x6a, 0x32, 0x5c, 0xa6, 0x4a, 0xbe,
	0x99, 0xd6, 0xf9, 0x34, 0xde, 0x0a, 0xf4, 0x9c, 0xb4, 0xe1, 0x9b, 0xe6, 0x15, 0x7b, 0x84, 0xe6,
	0xd1, 0xc3, 0x6a, 0x32, 0xa8, 0x4d, 0x8c, 0xa7, 0x71, 0x8d, 0xe9, 0x98, 0xb4, 0x0b, 0xae, 0x41,
	0xb1, 0x96, 0xf3, 0xe2, 0x7a, 0x43, 0x4f, 0x49, 0xc7, 0x2c, 0x55, 0x06, 0x92, 0xb5, 0x31, 0xde,
	0xee, 0xe8, 0x27, 0x32, 0xb0, 0x60, 0x53, 0x99, 0x98, 0x45, 0x59, 0xca, 0x25, 0xeb, 0xe0, 0xf0,
	0xf0, 0x6e, 0x35, 0x69, 0xfc, 0x59, 0x4d, 0xce, 0xe7, 0xc2, 0xde, 0x2c, 0xb2, 0x30, 0x07, 0x15,
	0xe5, 0x60, 0x14, 0x98, 0xed, 0xe7, 0xa5, 0x29, 0x6e, 0x23, 0xbb, 0x2c, 0xb9, 0x09, 0xaf, 0xb4,
	0x8d, 0xfb, 0x38, 0xe3, 0x33, 0x8e, 0xa0, 0x67, 0xa4, 0x5b, 0xf0, 0x5c, 0xa8, 0x54, 0x1a, 0xf6,
	0x38, 0xf0, 0x66, 0xed, 0x78, 0xb7, 0xa7, 0x01, 0xe9, 0x17, 0xdc, 0xe4, 0x95, 0x28, 0xdd, 0xc5,
	0xb1, 0x2e, 0xfe, 0xcb, 0x61, 0x44, 0x9f, 0x92, 0x1e, 0x1e, 0xf8, 0x8b, 0x50, 0x9c, 0xf5, 0xb0,
	0xbe, 0x0f, 0x68, 0x48, 0x4e, 0xb2, 0x45, 0xa5, 0x13, 0x3c, 0x6a, 0x52, 0x08, 0x93, 0x66, 0x92,
	0x17, 0x8c, 0x04, 0xde, 0xac, 0x1b, 0x1f, 0x3b, 0xf4, 0xd1, 0x91, 0x77, 0x5b, 0x40, 0x5f, 0x91,
	0x31, 0xfa, 0x37, 0x20, 0x8b, 0xc3, 0x42, 0x1f, 0x0b, 0xd4, 0xb1, 0x0f, 0x88, 0x76, 0x8d, 0x17,
	0x04, 0xd3, 0xe4, 0xba, 0x02, 0xb5, 0xf7, 0x07, 0xe8, 0x1f, 0x39, 0xf2, 0xbe, 0x02, 0xb5, 0xb3,
	0x2f, 0xc8, 0x93, 0xeb, 0x8a, 0xf3, 0x1f, 0x7c, 0xaf, 0x0e, 0x51, 0x1d, 0xd5, 0xf1, 0x4e, 0x7c,
	0x46, 0x86, 0x4a, 0x68, 0xbb, 0xd7, 0x46, 0xa8, 0x0d, 0x5c, 0xf8, 0x5f, 0xba, 0xbc, 0xb8, 0x5b,
	0xfb, 0xde, 0xfd, 0xda, 0xf7, 0xfe, 0xae, 0x7d, 0xef, 0xe7, 0xc6, 0x6f, 0xdc, 0x6f, 0xfc, 0xc6,
	0xef, 0x8d, 0xdf, 0xf8, 0x3a, 0xfc, 0x1e, 0xd5, 0x4f, 0x11, 0xef, 0x3c, 0xeb, 0xe0, 0xdb, 0x7a,
	0xfd, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x45, 0x14, 0x13, 0xa0, 0x02, 0x00, 0x00,
}

func (m *CoinIssue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CoinIssue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CoinIssue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MintDisabled {
		i--
		if m.MintDisabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if m.FreezeDisabled {
		i--
		if m.FreezeDisabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x68
	}
	if m.BurnFromDisabled {
		i--
		if m.BurnFromDisabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if m.BurnHolderDisabled {
		i--
		if m.BurnHolderDisabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.BurnOwnerDisabled {
		i--
		if m.BurnOwnerDisabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.IssueTime != 0 {
		i = encodeVarintCoinIssue(dAtA, i, uint64(m.IssueTime))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintCoinIssue(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x42
	}
	if m.Decimals != 0 {
		i = encodeVarintCoinIssue(dAtA, i, uint64(m.Decimals))
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.TotalSupply.Size()
		i -= size
		if _, err := m.TotalSupply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCoinIssue(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintCoinIssue(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintCoinIssue(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintCoinIssue(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Issuer) > 0 {
		i -= len(m.Issuer)
		copy(dAtA[i:], m.Issuer)
		i = encodeVarintCoinIssue(dAtA, i, uint64(len(m.Issuer)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintCoinIssue(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCoinIssue(dAtA []byte, offset int, v uint64) int {
	offset -= sovCoinIssue(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CoinIssue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovCoinIssue(uint64(m.Id))
	}
	l = len(m.Issuer)
	if l > 0 {
		n += 1 + l + sovCoinIssue(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovCoinIssue(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovCoinIssue(uint64(l))
	}
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovCoinIssue(uint64(l))
	}
	l = m.TotalSupply.Size()
	n += 1 + l + sovCoinIssue(uint64(l))
	if m.Decimals != 0 {
		n += 1 + sovCoinIssue(uint64(m.Decimals))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovCoinIssue(uint64(l))
	}
	if m.IssueTime != 0 {
		n += 1 + sovCoinIssue(uint64(m.IssueTime))
	}
	if m.BurnOwnerDisabled {
		n += 2
	}
	if m.BurnHolderDisabled {
		n += 2
	}
	if m.BurnFromDisabled {
		n += 2
	}
	if m.FreezeDisabled {
		n += 2
	}
	if m.MintDisabled {
		n += 2
	}
	return n
}

func sovCoinIssue(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCoinIssue(x uint64) (n int) {
	return sovCoinIssue(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CoinIssue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCoinIssue
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CoinIssue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CoinIssue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoinIssue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoinIssue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoinIssue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoinIssue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Issuer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoinIssue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoinIssue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoinIssue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoinIssue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoinIssue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoinIssue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoinIssue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoinIssue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoinIssue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoinIssue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoinIssue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoinIssue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decimals", wireType)
			}
			m.Decimals = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoinIssue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Decimals |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoinIssue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCoinIssue
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCoinIssue
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssueTime", wireType)
			}
			m.IssueTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoinIssue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssueTime |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnOwnerDisabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoinIssue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BurnOwnerDisabled = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnHolderDisabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoinIssue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BurnHolderDisabled = bool(v != 0)
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnFromDisabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoinIssue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BurnFromDisabled = bool(v != 0)
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FreezeDisabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoinIssue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FreezeDisabled = bool(v != 0)
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintDisabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCoinIssue
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MintDisabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipCoinIssue(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCoinIssue
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCoinIssue(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCoinIssue
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCoinIssue
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCoinIssue
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCoinIssue
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCoinIssue
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCoinIssue
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCoinIssue        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCoinIssue          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCoinIssue = fmt.Errorf("proto: unexpected end of group")
)
