// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: konstellation/issue/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	IssueFee         github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,1,opt,name=issue_fee,json=issueFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"issue_fee"`
	MintFee          github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,2,opt,name=mint_fee,json=mintFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"mint_fee"`
	FreezeFee        github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,3,opt,name=freeze_fee,json=freezeFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"freeze_fee"`
	UnfreezeFee      github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,4,opt,name=unfreeze_fee,json=unfreezeFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"unfreeze_fee"`
	BurnFee          github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,5,opt,name=burn_fee,json=burnFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"burn_fee"`
	BurnFromFee      github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,6,opt,name=burn_from_fee,json=burnFromFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"burn_from_fee"`
	TransferOwnerFee github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,7,opt,name=transfer_owner_fee,json=transferOwnerFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"transfer_owner_fee"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_d569790a7800735e, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "konstellation.issue.Params")
}

func init() { proto.RegisterFile("konstellation/issue/params.proto", fileDescriptor_d569790a7800735e) }

var fileDescriptor_d569790a7800735e = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0xd2, 0xbf, 0x4a, 0x3b, 0x41,
	0x10, 0x07, 0xf0, 0xbb, 0xdf, 0x2f, 0xe6, 0xcf, 0x6a, 0x40, 0x4e, 0x0b, 0xb1, 0xd8, 0x04, 0x9b,
	0xd8, 0x78, 0x5b, 0xf8, 0x06, 0x11, 0x52, 0x88, 0xa8, 0xc4, 0x4e, 0x90, 0x70, 0x89, 0x93, 0x78,
	0x24, 0xbb, 0x13, 0x76, 0xf7, 0xf0, 0xcf, 0x53, 0xf8, 0x54, 0x92, 0x32, 0xa5, 0x58, 0x04, 0xb9,
	0x7b, 0x11, 0xd9, 0xb9, 0x0b, 0x68, 0xbb, 0xd5, 0x2e, 0xcc, 0x77, 0x3e, 0xcc, 0xc0, 0xb0, 0xee,
	0x1c, 0x95, 0xb1, 0xb0, 0x58, 0x24, 0x36, 0x45, 0x25, 0x52, 0x63, 0x32, 0x10, 0xcb, 0x44, 0x27,
	0xd2, 0xc4, 0x4b, 0x8d, 0x16, 0xa3, 0x83, 0x3f, 0x89, 0x98, 0x12, 0xc7, 0x87, 0x33, 0x9c, 0x21,
	0xd5, 0x85, 0xfb, 0x95, 0xd1, 0x93, 0x8f, 0x1a, 0xab, 0xdf, 0x52, 0x6f, 0x74, 0xc5, 0x5a, 0x94,
	0x1c, 0x4d, 0x01, 0x8e, 0xc2, 0x6e, 0x78, 0xda, 0xea, 0x8b, 0xd5, 0xa6, 0x13, 0x7c, 0x6d, 0x3a,
	0xbd, 0x59, 0x6a, 0x9f, 0xb2, 0x71, 0x3c, 0x41, 0x29, 0x26, 0x68, 0x24, 0x9a, 0xea, 0x39, 0x33,
	0x8f, 0x73, 0x61, 0x5f, 0x97, 0x60, 0xe2, 0x0b, 0x4c, 0xd5, 0xb0, 0x49, 0xc2, 0x00, 0x20, 0xba,
	0x64, 0x4d, 0x99, 0x2a, 0x4b, 0xd8, 0x3f, 0x3f, 0xac, 0xe1, 0x00, 0x67, 0x5d, 0x33, 0x36, 0xd5,
	0x00, 0x6f, 0xe5, 0x68, 0xff, 0xfd, 0xb4, 0x56, 0x49, 0x38, 0x6f, 0xc8, 0xf6, 0x32, 0xf5, 0x4b,
	0xac, 0xf9, 0x89, 0xbb, 0x5b, 0xa4, 0xda, 0x77, 0x9c, 0x69, 0x45, 0xde, 0x8e, 0xe7, 0xbe, 0x0e,
	0x70, 0xd6, 0x1d, 0x6b, 0x97, 0x96, 0x46, 0x49, 0x60, 0xdd, 0x73, 0x40, 0x02, 0x35, 0x4a, 0x87,
	0x3e, 0xb0, 0xc8, 0xea, 0x44, 0x99, 0x29, 0xe8, 0x11, 0x3e, 0x2b, 0xd0, 0x24, 0x37, 0xfc, 0xe4,
	0xfd, 0x2d, 0x75, 0xe3, 0xa4, 0x01, 0x40, 0xbf, 0xb7, 0xca, 0x79, 0xb8, 0xce, 0x79, 0xf8, 0x9d,
	0xf3, 0xf0, 0xbd, 0xe0, 0xc1, 0xba, 0xe0, 0xc1, 0x67, 0xc1, 0x83, 0xfb, 0xf6, 0x4b, 0x75, 0xa3,
	0xd4, 0x3f, 0xae, 0xd3, 0xe1, 0x9d, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x96, 0xf7, 0x55,
	0xc7, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TransferOwnerFee.Size()
		i -= size
		if _, err := m.TransferOwnerFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.BurnFromFee.Size()
		i -= size
		if _, err := m.BurnFromFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.BurnFee.Size()
		i -= size
		if _, err := m.BurnFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.UnfreezeFee.Size()
		i -= size
		if _, err := m.UnfreezeFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.FreezeFee.Size()
		i -= size
		if _, err := m.FreezeFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.MintFee.Size()
		i -= size
		if _, err := m.MintFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.IssueFee.Size()
		i -= size
		if _, err := m.IssueFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.IssueFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MintFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.FreezeFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.UnfreezeFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.BurnFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.BurnFromFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.TransferOwnerFee.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssueFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.IssueFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MintFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FreezeFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FreezeFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnfreezeFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UnfreezeFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BurnFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnFromFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BurnFromFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferOwnerFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TransferOwnerFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
