// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSetExchangeRate struct {
	ExchangeRate *types.Coin `protobuf:"bytes,1,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	Setter       string      `protobuf:"bytes,2,opt,name=setter,proto3" json:"setter,omitempty"`
}

func (m *MsgSetExchangeRate) Reset()         { *m = MsgSetExchangeRate{} }
func (m *MsgSetExchangeRate) String() string { return proto.CompactTextString(m) }
func (*MsgSetExchangeRate) ProtoMessage()    {}
func (*MsgSetExchangeRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fd2153dc07d3b5c, []int{0}
}
func (m *MsgSetExchangeRate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetExchangeRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetExchangeRate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetExchangeRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetExchangeRate.Merge(m, src)
}
func (m *MsgSetExchangeRate) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetExchangeRate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetExchangeRate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetExchangeRate proto.InternalMessageInfo

func (m *MsgSetExchangeRate) GetExchangeRate() *types.Coin {
	if m != nil {
		return m.ExchangeRate
	}
	return nil
}

func (m *MsgSetExchangeRate) GetSetter() string {
	if m != nil {
		return m.Setter
	}
	return ""
}

type MsgSetExchangeRateResponse struct {
}

func (m *MsgSetExchangeRateResponse) Reset()         { *m = MsgSetExchangeRateResponse{} }
func (m *MsgSetExchangeRateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetExchangeRateResponse) ProtoMessage()    {}
func (*MsgSetExchangeRateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fd2153dc07d3b5c, []int{1}
}
func (m *MsgSetExchangeRateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetExchangeRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetExchangeRateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetExchangeRateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetExchangeRateResponse.Merge(m, src)
}
func (m *MsgSetExchangeRateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetExchangeRateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetExchangeRateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetExchangeRateResponse proto.InternalMessageInfo

type MsgDeleteExchangeRate struct {
	Denom   string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgDeleteExchangeRate) Reset()         { *m = MsgDeleteExchangeRate{} }
func (m *MsgDeleteExchangeRate) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteExchangeRate) ProtoMessage()    {}
func (*MsgDeleteExchangeRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fd2153dc07d3b5c, []int{2}
}
func (m *MsgDeleteExchangeRate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteExchangeRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteExchangeRate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteExchangeRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteExchangeRate.Merge(m, src)
}
func (m *MsgDeleteExchangeRate) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteExchangeRate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteExchangeRate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteExchangeRate proto.InternalMessageInfo

func (m *MsgDeleteExchangeRate) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MsgDeleteExchangeRate) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgDeleteExchangeRateResponse struct {
}

func (m *MsgDeleteExchangeRateResponse) Reset()         { *m = MsgDeleteExchangeRateResponse{} }
func (m *MsgDeleteExchangeRateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteExchangeRateResponse) ProtoMessage()    {}
func (*MsgDeleteExchangeRateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fd2153dc07d3b5c, []int{3}
}
func (m *MsgDeleteExchangeRateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteExchangeRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteExchangeRateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteExchangeRateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteExchangeRateResponse.Merge(m, src)
}
func (m *MsgDeleteExchangeRateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteExchangeRateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteExchangeRateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteExchangeRateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSetExchangeRate)(nil), "types.MsgSetExchangeRate")
	proto.RegisterType((*MsgSetExchangeRateResponse)(nil), "types.MsgSetExchangeRateResponse")
	proto.RegisterType((*MsgDeleteExchangeRate)(nil), "types.MsgDeleteExchangeRate")
	proto.RegisterType((*MsgDeleteExchangeRateResponse)(nil), "types.MsgDeleteExchangeRateResponse")
}

func init() { proto.RegisterFile("tx.proto", fileDescriptor_0fd2153dc07d3b5c) }

var fileDescriptor_0fd2153dc07d3b5c = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x3b, 0x4a, 0xab, 0xbd, 0xfe, 0xc1, 0xa0, 0xd2, 0x86, 0x3a, 0xd6, 0xe0, 0xa2, 0xab,
	0x09, 0xad, 0x7b, 0x17, 0xfe, 0xe0, 0x2a, 0x08, 0x71, 0x23, 0x6e, 0x64, 0x12, 0x2f, 0xb1, 0x90,
	0x66, 0x42, 0xe6, 0x22, 0xf1, 0x2d, 0x7c, 0x14, 0x1f, 0xc3, 0x65, 0x97, 0x2e, 0x25, 0x79, 0x11,
	0x21, 0x4d, 0xf0, 0x27, 0xd5, 0xe5, 0xe1, 0x70, 0xbe, 0x73, 0x66, 0x2e, 0xac, 0x53, 0x26, 0x93,
	0x54, 0x93, 0xe6, 0x6d, 0x7a, 0x4e, 0xd0, 0x58, 0xfc, 0x69, 0xec, 0x23, 0xa9, 0xb1, 0x13, 0xe8,
	0x69, 0xbc, 0xb0, 0xec, 0x08, 0xb8, 0x6b, 0xc2, 0x1b, 0xa4, 0xcb, 0x2c, 0x78, 0x54, 0x71, 0x88,
	0x9e, 0x22, 0xe4, 0xa7, 0xb0, 0x85, 0x95, 0xbe, 0x4f, 0x15, 0x61, 0x8f, 0x0d, 0xd9, 0x68, 0x63,
	0xd2, 0x97, 0x81, 0x36, 0x33, 0x6d, 0xa4, 0xaf, 0x0c, 0xca, 0x8a, 0x26, 0xcf, 0xf5, 0x34, 0xf6,
	0x36, 0xf1, 0x7b, 0x7e, 0x1f, 0x3a, 0x06, 0x89, 0x30, 0xed, 0xad, 0x0c, 0xd9, 0xa8, 0xeb, 0x55,
	0xca, 0x1e, 0x80, 0xd5, 0x6c, 0xf3, 0xd0, 0x24, 0x3a, 0x36, 0x68, 0x5f, 0xc1, 0x9e, 0x6b, 0xc2,
	0x0b, 0x8c, 0x90, 0xf0, 0xc7, 0x9c, 0x5d, 0x68, 0x3f, 0x60, 0xac, 0x67, 0xe5, 0x8c, 0xae, 0xb7,
	0x10, 0xbc, 0x07, 0x6b, 0x41, 0x8a, 0x8a, 0x74, 0xdd, 0x52, 0x4b, 0xfb, 0x10, 0x0e, 0x96, 0x82,
	0xea, 0xa6, 0xc9, 0x2b, 0x83, 0x55, 0xd7, 0x84, 0xfc, 0x1a, 0x76, 0x7e, 0x3f, 0xbd, 0x2f, 0xcb,
	0xcf, 0x92, 0xcd, 0x9d, 0xd6, 0xd1, 0x9f, 0x56, 0x0d, 0xe6, 0xb7, 0xc0, 0x97, 0xec, 0x1f, 0x7c,
	0x05, 0x9b, 0xae, 0x75, 0xfc, 0x9f, 0x5b, 0x93, 0xcf, 0x46, 0x6f, 0xb9, 0x60, 0xf3, 0x5c, 0xb0,
	0x8f, 0x5c, 0xb0, 0x97, 0x42, 0xb4, 0xe6, 0x85, 0x68, 0xbd, 0x17, 0xa2, 0x75, 0xb7, 0x9d, 0x39,
	0x3a, 0x55, 0x41, 0x84, 0x4e, 0xc9, 0xf1, 0x3b, 0xe5, 0x65, 0x4f, 0x3e, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x06, 0x1f, 0xcb, 0x55, 0x00, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SetExchangeRate(ctx context.Context, in *MsgSetExchangeRate, opts ...grpc.CallOption) (*MsgSetExchangeRateResponse, error)
	DeleteExchangeRate(ctx context.Context, in *MsgDeleteExchangeRate, opts ...grpc.CallOption) (*MsgDeleteExchangeRateResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetExchangeRate(ctx context.Context, in *MsgSetExchangeRate, opts ...grpc.CallOption) (*MsgSetExchangeRateResponse, error) {
	out := new(MsgSetExchangeRateResponse)
	err := c.cc.Invoke(ctx, "/types.Msg/SetExchangeRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteExchangeRate(ctx context.Context, in *MsgDeleteExchangeRate, opts ...grpc.CallOption) (*MsgDeleteExchangeRateResponse, error) {
	out := new(MsgDeleteExchangeRateResponse)
	err := c.cc.Invoke(ctx, "/types.Msg/DeleteExchangeRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SetExchangeRate(context.Context, *MsgSetExchangeRate) (*MsgSetExchangeRateResponse, error)
	DeleteExchangeRate(context.Context, *MsgDeleteExchangeRate) (*MsgDeleteExchangeRateResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SetExchangeRate(ctx context.Context, req *MsgSetExchangeRate) (*MsgSetExchangeRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetExchangeRate not implemented")
}
func (*UnimplementedMsgServer) DeleteExchangeRate(ctx context.Context, req *MsgDeleteExchangeRate) (*MsgDeleteExchangeRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExchangeRate not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SetExchangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetExchangeRate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetExchangeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/SetExchangeRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetExchangeRate(ctx, req.(*MsgSetExchangeRate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteExchangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteExchangeRate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteExchangeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.Msg/DeleteExchangeRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteExchangeRate(ctx, req.(*MsgDeleteExchangeRate))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetExchangeRate",
			Handler:    _Msg_SetExchangeRate_Handler,
		},
		{
			MethodName: "DeleteExchangeRate",
			Handler:    _Msg_DeleteExchangeRate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tx.proto",
}

func (m *MsgSetExchangeRate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetExchangeRate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetExchangeRate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Setter) > 0 {
		i -= len(m.Setter)
		copy(dAtA[i:], m.Setter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Setter)))
		i--
		dAtA[i] = 0x12
	}
	if m.ExchangeRate != nil {
		{
			size, err := m.ExchangeRate.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetExchangeRateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetExchangeRateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetExchangeRateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteExchangeRate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteExchangeRate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteExchangeRate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteExchangeRateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteExchangeRateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteExchangeRateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetExchangeRate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ExchangeRate != nil {
		l = m.ExchangeRate.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Setter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetExchangeRateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteExchangeRate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteExchangeRateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetExchangeRate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetExchangeRate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetExchangeRate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExchangeRate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExchangeRate == nil {
				m.ExchangeRate = &types.Coin{}
			}
			if err := m.ExchangeRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Setter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Setter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetExchangeRateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetExchangeRateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetExchangeRateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteExchangeRate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteExchangeRate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteExchangeRate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteExchangeRateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteExchangeRateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteExchangeRateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
